### ISSUE TITLE
xban.db file wipes itself out after some 65536 limit is hit

### ISSUE THREAD

**Issue by redblade7** [minetest-mods/xban2#19]
Hi,

I recently discovered that at one point in April 2019 on one of my servers, my xban.db file was wiped out.

Around the time it happened, debug.txt turns this message up:

> WARNING[Main]: [xban] Unable to load database: Deserialization failed: (load):378023: main function has more than 65536 constants

I don't know what "constants" are and wasn't paying attention to when this happened, but I don't think there were 65536 entries in xban.db at the time.

Also, I don't have the xban.db to offer you, but based the most recent server backup I have before this happened, 378023 is probably a line number in xban.db.

The most recent version of the mod was being used (February 12, 2019)

Sorry I can't offer more information on this.

**Comment by Lejo1** [comment]
I also had this problem(The reason why I switched to sban)
You could use one of this ways to safe the data instead:
https://github.com/minetest/minetest/issues/7574#issuecomment-406793673
