### ISSUE TITLE
Someone on a permaban AND temporary ban gets unbanned at expiration time

### ISSUE THREAD

**Issue by mgl512** [minetest-mods/xban2#9]
It's not the behavior you would expect. 

Two people banned the same player. One forever (/xban) and one temporarily (/xtempban). When the temporary ban expired, he could play. /xban_record showed the two bans but the expiration time of the temporary one was always now, the time at which the command was run. And the permaban was ignored when the player tried to log in.

**Comment by kaeza** [comment]
Thank you for reporting.
